### ISSUE TITLE
bytes error with new python-frontmatter

### ISSUE THREAD

**Issue by palewire** [datadesk/django-bigbuild#39]
Python 3 builds failing now with the new python-frontmatter. Something about how it's converting our Post object for writing? Any ideas @eyeseast?

```python
.E.
======================================================================
ERROR: setUpClass (bigbuild.tests.FakePagesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/datadesk/django-bigbuild/bigbuild/tests.py", line 79, in setUpClass
    [p.create_directory() for p in pages]
  File "/home/travis/build/datadesk/django-bigbuild/bigbuild/tests.py", line 79, in <listcomp>
    [p.create_directory() for p in pages]
  File "/home/travis/build/datadesk/django-bigbuild/bigbuild/models/pages.py", line 70, in create_directory
    self.write_frontmatter()
  File "/home/travis/build/datadesk/django-bigbuild/bigbuild/models/pages.py", line 95, in write_frontmatter
    frontmatter.dump(self, path or self.frontmatter_path)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/frontmatter/__init__.py", line 159, in dump
    f.write(content)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/codecs.py", line 718, in write
    return self.writer.write(data)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/codecs.py", line 376, in write
    data, consumed = self.encode(object, self.errors)
TypeError: Can't convert 'bytes' object to str implicitly
----------------------------------------------------------------------
```

**Comment by eyeseast** [comment]
Yup, that's a bug. Fixing it now.

**Comment by eyeseast** [comment]
OK, bugfix pushed: https://pypi.python.org/pypi/python-frontmatter/0.4.2

Problem was where the exported post was getting encoded on the way out. When we already have a file descriptor, it should get encoded to bytes right as it's written. When we're opening with `codecs.open`, we need unicode text still.

So that's fixed now, with a new test.

**Comment by palewire** [comment]
Thank you.
